// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID              string  `json:"id"`
	BookName        *string `json:"bookName"`
	BookDescription *string `json:"bookDescription"`
	BookAuthorName  *string `json:"bookAuthorName"`
}

type BookID struct {
	ID *int `json:"id"`
}

type BookInput struct {
	BookName        string `json:"bookName"`
	BookDescription string `json:"bookDescription"`
	BookAuthorName  string `json:"bookAuthorName"`
}

type DBConfig struct {
	Host     string `json:"host"`
	Port     string `json:"port"`
	User     string `json:"user"`
	DbName   string `json:"dbName"`
	Password string `json:"password"`
}
